Optionally install plugins on startup
Add support for an environment variable (INSTALL_PLUGINS) that allows
installing a set of plugins on image startup. The format of the variable
is a set of comma-separated strings of the form [plugin-id]:[version].
Example:
INSTALL_PLUGINS=groovy:1.30,github-pr-comment-build:1.1

When used with persistent storage, plugin download/installation would
only happen the very first time the image is run.

diff --git a/2/test/run b/2/test/run
--- a/2/test/run
+++ b/2/test/run
@@ -201,6 +201,20 @@ function run_s2i_tests() {
     return 1
   fi
 
+  if [[ -n "{VERIFY_INSTALLED:-}" ]]; then
+	  if ! docker exec ${cid} ls /var/lib/jenkins/plugins/${VERIFY_INSTALLED}.jpi; then
+		  echo "Fail: the ${VERIFY_INSTALLED} plugin was not installed."
+		  return 1
+      fi
+  fi
+
+  if [[ -n "{VERIFY_NOT_INSTALLED:-}" ]]; then
+	  if docker exec ${cid} ls /var/lib/jenkins/plugins/${VERIFY_NOT_INSTALLED}.jpi; then
+		  echo "Fail: the ${VERIFY_NOT_INSTALLED} plugin was installed."
+		  return 1
+      fi
+  fi
+
   test_get_job admin password sample-app-test
   test_create_job admin password testJob
   test_get_job admin password testJob
@@ -210,15 +224,26 @@ function run_s2i_tests() {
 
 # Normal tests
 echo "Normal test: 64 bit"
+VERIFY_NOT_INSTALLED=ghprb
 CONTAINER_ARGS="-u 10000:0 -e OPENSHIFT_JENKINS_JVM_ARCH=x86_64"
 run_tests jenkins_test
 cleanup
 sleep 5
 echo "Normal test: 32 bit"
 CIDFILE_DIR=$(mktemp --suffix=jenkins_test_cidfiles -d)
-VOLUME=`mktemp -d`
+VOLUME=$(mktemp -d)
 chmod a+rwx $VOLUME
 CONTAINER_ARGS="-u 10000:0 -e OPENSHIFT_JENKINS_JVM_ARCH=i386 "
+run_tests jenkins_test
+cleanup
+sleep 5
+echo "Test: install plugins on start"
+CIDFILE_DIR=$(mktemp --suffix=jenkins_test_cidfiles -d)
+VOLUME=$(mktemp -d)
+chmod a+rwx $VOLUME
+VERIFY_INSTALLED=ghprb
+VERIFY_NOT_INSTALLED=""
+CONTAINER_ARGS="-u 10000:0 -e OPENSHIFT_JENKINS_JVM_ARCH=x86_64 -e INSTALL_PLUGINS=ghprb:1.35.0"
 run_tests jenkins_test
 
 # S2I tests
