re-bump to LTS v2.19.3, update related plugins, and add tests to confirm plugins load successfully
This reverts commit 9ff112fbae7bc66c13def4091459b1dd47ba81cd.

diff --git a/2/test/run b/2/test/run
--- a/2/test/run
+++ b/2/test/run
@@ -107,6 +107,18 @@ function run_tests() {
   create_container $name $VOLUME
   CONTAINER_IP=$(get_container_ip $name)
   test_connection $name
+
+  # Make sure no plugins failed to load
+  set +e
+  CONTAINER=$(cat $cidfile)
+  docker logs $CONTAINER |& grep "Failed Loading plugin"
+  rc=$?
+  set -e
+  if [ $rc -eq 0 ]; then
+    echo "Failed loading plugins"
+    return 1
+  fi
+
   test_create_job admin password testJob
   test_get_job admin password testJob
   set +e
